In [6]:
import numpy as np

a = np.array([[1,2], [3,4]])
print(a.shape)

b = np.array([[5,6], [7,8]])
print(b.shape)

print(np.dot(a,b)) # np.dot / 두 행렬의 곱을 계산한다. 입력이 1차원 배열이면 벡터를, 2차원 배열(행렬)이면 행렬 곱을 계산한다.

print("ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ")

A = np.array([[1,2,3], [4,5,6]])
print(A.shape)

B = np.array([[1,2], [3,4], [5,6]])
print(B.shape)

# 행렬끼리의 곱셈은 첫번째 행렬(A)의 열 수와 두번째 행렬(B)의 행 수가 같아야 계산할 수 있다. 곱한 결과는 A의 열 수(B의 행 수) 차원의 배열이 된다.
print(np.dot(A,B))

# 위 조건이 성립하면 1차원 배열도 행렬 곱 계산이 가능하다.
D = np.array([7,8])
print(np.dot(B,D))

C = np.array([[1,2], [3,4]])

# A의 열의 원소 수와 C의 행의 원소 수가 달라서 계산 시에 ValueError 발생
print(np.dot(A,C))

(2, 2)
(2, 2)
[[19 22]
 [43 50]]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
(2, 3)
(3, 2)
[[22 28]
 [49 64]]
[23 53 83]


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)